In [1]:
import numpy as np
import pandas as pd
import sklearn

In [2]:
df=pd.read_csv('/content/Iris.csv')
df=df.drop(['Id'],axis=1)
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
df['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [4]:
df['Species']=df['Species'].map({'Iris-setosa':0,'Iris-versicolor':1,'Iris-virginica':2})

In [5]:
print(df)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0              5.1           3.5            1.4           0.2        0
1              4.9           3.0            1.4           0.2        0
2              4.7           3.2            1.3           0.2        0
3              4.6           3.1            1.5           0.2        0
4              5.0           3.6            1.4           0.2        0
..             ...           ...            ...           ...      ...
145            6.7           3.0            5.2           2.3        2
146            6.3           2.5            5.0           1.9        2
147            6.5           3.0            5.2           2.0        2
148            6.2           3.4            5.4           2.3        2
149            5.9           3.0            5.1           1.8        2

[150 rows x 5 columns]


In [6]:
df.sample(7)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
121            5.6           2.8            4.9           2.0        2
142            5.8           2.7            5.1           1.9        2
117            7.7           3.8            6.7           2.2        2
88             5.6           3.0            4.1           1.3        1
114            5.8           2.8            5.1           2.4        2
146            6.3           2.5            5.0           1.9        2
86             6.7           3.1            4.7           1.5        1

In [7]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)
training_data=pd.DataFrame()
training_data=x_train.copy()
training_data['y_train']=y_train
print(training_data)
testing_data=pd.DataFrame()
testing_data=x_test.copy()
testing_data['y_test']=y_test
print(testing_data)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  y_train
81             5.5           2.4            3.7           1.0        1
133            6.3           2.8            5.1           1.5        2
137            6.4           3.1            5.5           1.8        2
75             6.6           3.0            4.4           1.4        1
109            7.2           3.6            6.1           2.5        2
..             ...           ...            ...           ...      ...
71             6.1           2.8            4.0           1.3        1
106            4.9           2.5            4.5           1.7        2
14             5.8           4.0            1.2           0.2        0
92             5.8           2.6            4.0           1.2        1
102            7.1           3.0            5.9           2.1        2

[105 rows x 5 columns]
     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  y_test
73             6.1           2.8            4.7       

In [9]:
from sklearn.neighbors import KNeighborsClassifier
reg=KNeighborsClassifier(n_neighbors=5)
reg.fit(x_train,y_train)

KNeighborsClassifier()

In [10]:
y_train_pred=reg.predict(x_train)
training_data['y_train_pred']=y_train_pred
training_data

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  y_train  \
81             5.5           2.4            3.7           1.0        1   
133            6.3           2.8            5.1           1.5        2   
137            6.4           3.1            5.5           1.8        2   
75             6.6           3.0            4.4           1.4        1   
109            7.2           3.6            6.1           2.5        2   
..             ...           ...            ...           ...      ...   
71             6.1           2.8            4.0           1.3        1   
106            4.9           2.5            4.5           1.7        2   
14             5.8           4.0            1.2           0.2        0   
92             5.8           2.6            4.0           1.2        1   
102            7.1           3.0            5.9           2.1        2   

     y_train_pred  
81              1  
133             2  
137             2  
75              1  
109             2  
..            ...  
71              1  
106             1  
14              0  
92              1  
102             2  

[105 rows x 6 columns]

In [11]:
y_test_pred=reg.predict(x_test)
testing_data['y_test_pred']=y_test_pred
print(testing_data)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  y_test  \
73             6.1           2.8            4.7           1.2       1   
18             5.7           3.8            1.7           0.3       0   
118            7.7           2.6            6.9           2.3       2   
78             6.0           2.9            4.5           1.5       1   
76             6.8           2.8            4.8           1.4       1   
31             5.4           3.4            1.5           0.4       0   
64             5.6           2.9            3.6           1.3       1   
141            6.9           3.1            5.1           2.3       2   
68             6.2           2.2            4.5           1.5       1   
82             5.8           2.7            3.9           1.2       1   
110            6.5           3.2            5.1           2.0       2   
12             4.8           3.0            1.4           0.1       0   
36             5.5           3.5            1.3    

In [12]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_train,y_train_pred))
print("accuracy of training data",accuracy_score(y_train,y_train_pred))

[[31  0  0]
 [ 0 33  4]
 [ 0  1 36]]
accuracy of training data 0.9523809523809523


In [13]:
confusion_matrix(y_test,y_test_pred)
print(confusion_matrix(y_test,y_test_pred))
print("accuracy of testing data",accuracy_score(y_test,y_test_pred))

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
accuracy of testing data 1.0


In [14]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

